# Generated by Django 4.1.2 on 2022-10-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ufoslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
