# Generated by Django 4.1.2 on 2022-10-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_ufoslider_delete_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ufoslider',
            new_name='ufoslide',
        ),
    ]
