# Generated by Django 4.1.2 on 2022-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rename_ufoslider_ufoslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufoslide',
            name='upload',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
