# Generated by Django 4.1.2 on 2022-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='color',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='style',
            field=models.CharField(default='', max_length=255),
        ),
    ]
