# Generated by Django 4.1.2 on 2022-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_remove_menuitem_color_menuitem_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='catslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
