# Generated by Django 4.1.2 on 2022-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_catslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='tamtam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='static/audio/')),
                ('upload', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
