# Generated by Django 4.1.2 on 2022-10-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_tamtam'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(upload_to='static/images/')),
                ('pic2', models.FileField(upload_to='static/images/')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('pathid', models.CharField(max_length=255)),
            ],
        ),
    ]
