# Generated by Django 4.1.2 on 2022-10-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_country_pathsvg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='pathsvg',
        ),
    ]
