# Generated by Django 4.1.2 on 2022-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_remove_country_pathsvg'),
    ]

    operations = [
        migrations.CreateModel(
            name='merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(upload_to='static/images/merch/')),
                ('pic2', models.FileField(upload_to='static/images/merch/')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
