# Generated by Django 4.1.2 on 2022-10-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
