# Generated by Django 4.1.2 on 2022-10-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
