# Generated by Django 4.1.2 on 2022-10-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_delete_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catslide',
        ),
        migrations.DeleteModel(
            name='tamtam',
        ),
    ]
